<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\User;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = User::take(3)->get();
        
        if ($users->isEmpty()) {
            $this->command->warn('No hay usuarios disponibles. Creando productos sin creador asignado.');
        }

        $products = [
            // Ropa y Textiles
            [
                'name' => 'Camisetas de Algodón para Niños',
                'description' => 'Pack de 5 camisetas de algodón 100% orgánico, tallas S, M, L. Perfectas para niños de 3 a 12 años. Colores variados: azul, rojo, verde, amarillo y blanco.',
                'short_description' => 'Pack de 5 camisetas de algodón orgánico para niños',
                'category' => 'Ropa',
                'subcategory' => 'Niños',
                'tags' => ['ropa', 'niños', 'algodón', 'orgánico', 'camisetas'],
                'stock_quantity' => 50,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 150.00,
                'suggested_price' => 200.00,
                'currency' => 'GTQ',
                'weight' => 0.5,
                'length' => 30,
                'width' => 25,
                'height' => 2,
                'is_active' => true,
                'is_featured' => true,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de empresa textil',
                'received_date' => now()->subDays(10),
                'condition' => 'new',
                'specifications' => [
                    'Material' => 'Algodón 100% orgánico',
                    'Tallas disponibles' => 'S, M, L',
                    'Colores' => 'Azul, Rojo, Verde, Amarillo, Blanco',
                    'Edad recomendada' => '3-12 años',
                    'Cuidado' => 'Lavable en máquina'
                ],
                'usage_instructions' => 'Lavar antes del primer uso. Ideal para uso diario y actividades escolares.',
                'care_instructions' => 'Lavar en agua fría, no usar blanqueador, secar al aire libre.',
                'ngo_notes' => 'Donación recibida en excelente estado. Perfectas para distribución en comunidades rurales.',
                'created_by' => $users->first()?->id,
            ],
            [
                'name' => 'Zapatos Deportivos para Adultos',
                'description' => 'Zapatos deportivos de cuero sintético, tallas 6-10. Ideales para caminar y actividades diarias. Suela antideslizante y cómoda.',
                'short_description' => 'Zapatos deportivos cómodos para adultos',
                'category' => 'Calzado',
                'subcategory' => 'Adultos',
                'tags' => ['zapatos', 'deportivos', 'adultos', 'cómodos'],
                'stock_quantity' => 25,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 300.00,
                'suggested_price' => 400.00,
                'currency' => 'GTQ',
                'weight' => 0.8,
                'length' => 35,
                'width' => 25,
                'height' => 15,
                'is_active' => true,
                'is_featured' => false,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de tienda deportiva',
                'received_date' => now()->subDays(5),
                'condition' => 'like_new',
                'specifications' => [
                    'Material' => 'Cuero sintético',
                    'Tallas' => '6, 7, 8, 9, 10',
                    'Suela' => 'Antideslizante',
                    'Color' => 'Negro',
                    'Tipo' => 'Deportivo'
                ],
                'usage_instructions' => 'Ideal para caminar, correr y actividades deportivas ligeras.',
                'care_instructions' => 'Limpiar con paño húmedo, no sumergir en agua.',
                'ngo_notes' => 'Zapatos en muy buen estado, perfectos para trabajadores de campo.',
                'created_by' => $users->skip(1)->first()?->id,
            ],
            [
                'name' => 'Libros Educativos para Primaria',
                'description' => 'Colección de 20 libros educativos para niños de primaria. Incluye matemáticas, español, ciencias naturales y estudios sociales.',
                'short_description' => 'Colección de libros educativos para primaria',
                'category' => 'Educación',
                'subcategory' => 'Libros',
                'tags' => ['libros', 'educación', 'primaria', 'niños', 'aprendizaje'],
                'stock_quantity' => 15,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 500.00,
                'suggested_price' => 600.00,
                'currency' => 'GTQ',
                'weight' => 2.0,
                'length' => 25,
                'width' => 20,
                'height' => 15,
                'is_active' => true,
                'is_featured' => true,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de editorial educativa',
                'received_date' => now()->subDays(15),
                'condition' => 'new',
                'specifications' => [
                    'Cantidad' => '20 libros',
                    'Nivel' => 'Primaria (1-6 grado)',
                    'Materias' => 'Matemáticas, Español, Ciencias, Estudios Sociales',
                    'Idioma' => 'Español',
                    'Formato' => 'Tapa blanda'
                ],
                'usage_instructions' => 'Ideal para bibliotecas escolares y programas de alfabetización.',
                'care_instructions' => 'Mantener en lugar seco, evitar humedad.',
                'ngo_notes' => 'Libros nuevos, perfectos para escuelas rurales sin recursos.',
                'created_by' => $users->first()?->id,
            ],
            [
                'name' => 'Kit de Higiene Personal',
                'description' => 'Kit completo de higiene personal que incluye: cepillo de dientes, pasta dental, jabón, champú, toalla y peine. Para uso individual.',
                'short_description' => 'Kit completo de higiene personal',
                'category' => 'Higiene',
                'subcategory' => 'Personal',
                'tags' => ['higiene', 'personal', 'kit', 'salud', 'básico'],
                'stock_quantity' => 100,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 75.00,
                'suggested_price' => 100.00,
                'currency' => 'GTQ',
                'weight' => 0.3,
                'length' => 20,
                'width' => 15,
                'height' => 8,
                'is_active' => true,
                'is_featured' => false,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de empresa de productos de higiene',
                'received_date' => now()->subDays(3),
                'condition' => 'new',
                'specifications' => [
                    'Contenido' => 'Cepillo, pasta, jabón, champú, toalla, peine',
                    'Uso' => 'Individual',
                    'Duración' => '1-2 meses',
                    'Edad' => 'Todas las edades',
                    'Tipo' => 'Básico'
                ],
                'usage_instructions' => 'Kit completo para mantener higiene personal diaria.',
                'care_instructions' => 'Mantener en lugar seco y fresco.',
                'ngo_notes' => 'Kits nuevos, esenciales para familias en situación vulnerable.',
                'created_by' => $users->skip(2)->first()?->id,
            ],
            [
                'name' => 'Tablet Educativa para Niños',
                'description' => 'Tablet Android con aplicaciones educativas preinstaladas. Incluye protector de pantalla, funda y cargador. Ideal para aprendizaje digital.',
                'short_description' => 'Tablet educativa con aplicaciones preinstaladas',
                'category' => 'Tecnología',
                'subcategory' => 'Educación',
                'tags' => ['tablet', 'educación', 'tecnología', 'niños', 'digital'],
                'stock_quantity' => 8,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 800.00,
                'suggested_price' => 1000.00,
                'currency' => 'GTQ',
                'weight' => 0.6,
                'length' => 25,
                'width' => 18,
                'height' => 1,
                'is_active' => true,
                'is_featured' => true,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de empresa tecnológica',
                'received_date' => now()->subDays(7),
                'condition' => 'like_new',
                'specifications' => [
                    'Sistema operativo' => 'Android 10',
                    'Pantalla' => '10 pulgadas',
                    'Almacenamiento' => '32GB',
                    'RAM' => '3GB',
                    'Incluye' => 'Protector, funda, cargador'
                ],
                'usage_instructions' => 'Ideal para programas de educación digital en comunidades rurales.',
                'care_instructions' => 'Mantener alejado del agua, limpiar pantalla con paño suave.',
                'ngo_notes' => 'Tablets en excelente estado, perfectas para centros comunitarios.',
                'created_by' => $users->first()?->id,
            ],
            [
                'name' => 'Ropa de Cama Completa',
                'description' => 'Juego de ropa de cama que incluye: sábana bajera, sábana encimera, funda de almohada y manta. Tamaño individual, algodón 100%.',
                'short_description' => 'Juego completo de ropa de cama individual',
                'category' => 'Hogar',
                'subcategory' => 'Ropa de Cama',
                'tags' => ['ropa de cama', 'hogar', 'algodón', 'individual', 'completo'],
                'stock_quantity' => 30,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 200.00,
                'suggested_price' => 250.00,
                'currency' => 'GTQ',
                'weight' => 1.2,
                'length' => 40,
                'width' => 30,
                'height' => 10,
                'is_active' => true,
                'is_featured' => false,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de tienda de hogar',
                'received_date' => now()->subDays(12),
                'condition' => 'new',
                'specifications' => [
                    'Tamaño' => 'Individual',
                    'Material' => 'Algodón 100%',
                    'Incluye' => 'Sábana bajera, encimera, funda, manta',
                    'Color' => 'Blanco',
                    'Cuidado' => 'Lavable en máquina'
                ],
                'usage_instructions' => 'Juego completo para cama individual, ideal para dormitorios.',
                'care_instructions' => 'Lavar en agua fría, no usar blanqueador, secar al aire.',
                'ngo_notes' => 'Ropa de cama nueva, esencial para familias que inician su hogar.',
                'created_by' => $users->skip(1)->first()?->id,
            ],
            [
                'name' => 'Material de Construcción - Cemento',
                'description' => 'Bolsas de cemento de 50kg cada una. Material de construcción de alta calidad para proyectos de vivienda social.',
                'short_description' => 'Cemento para construcción, bolsas de 50kg',
                'category' => 'Construcción',
                'subcategory' => 'Materiales',
                'tags' => ['construcción', 'cemento', 'material', 'vivienda', 'proyecto'],
                'stock_quantity' => 200,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 45.00,
                'suggested_price' => 50.00,
                'currency' => 'GTQ',
                'weight' => 50.0,
                'length' => 60,
                'width' => 40,
                'height' => 15,
                'is_active' => true,
                'is_featured' => false,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de empresa cementera',
                'received_date' => now()->subDays(20),
                'condition' => 'new',
                'specifications' => [
                    'Peso' => '50kg por bolsa',
                    'Tipo' => 'Cemento Portland',
                    'Uso' => 'Construcción general',
                    'Almacenamiento' => 'Lugar seco',
                    'Vida útil' => '6 meses'
                ],
                'usage_instructions' => 'Ideal para proyectos de construcción de vivienda social.',
                'care_instructions' => 'Almacenar en lugar seco, proteger de la humedad.',
                'ngo_notes' => 'Material de construcción donado para proyectos de vivienda.',
                'created_by' => $users->skip(2)->first()?->id,
            ],
            [
                'name' => 'Juguetes Educativos - Bloques de Construcción',
                'description' => 'Set de 100 bloques de construcción de plástico no tóxico. Incluye diferentes formas y colores. Ideal para desarrollo motor y creatividad.',
                'short_description' => 'Set de bloques de construcción para niños',
                'category' => 'Juguetes',
                'subcategory' => 'Educativos',
                'tags' => ['juguetes', 'educativos', 'bloques', 'niños', 'construcción'],
                'stock_quantity' => 12,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 120.00,
                'suggested_price' => 150.00,
                'currency' => 'GTQ',
                'weight' => 1.5,
                'length' => 30,
                'width' => 25,
                'height' => 20,
                'is_active' => true,
                'is_featured' => true,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de empresa de juguetes',
                'received_date' => now()->subDays(8),
                'condition' => 'new',
                'specifications' => [
                    'Cantidad' => '100 piezas',
                    'Material' => 'Plástico no tóxico',
                    'Edad' => '3-8 años',
                    'Colores' => 'Variados',
                    'Formas' => 'Diferentes geometrías'
                ],
                'usage_instructions' => 'Ideal para centros de cuidado infantil y programas educativos.',
                'care_instructions' => 'Lavar con agua y jabón suave, secar completamente.',
                'ngo_notes' => 'Juguetes nuevos, perfectos para programas de desarrollo infantil.',
                'created_by' => $users->first()?->id,
            ],
            [
                'name' => 'Medicamentos Básicos - Kit de Primeros Auxilios',
                'description' => 'Kit de primeros auxilios que incluye: vendas, gasas, alcohol, agua oxigenada, termómetro, tijeras y medicamentos básicos.',
                'short_description' => 'Kit completo de primeros auxilios',
                'category' => 'Salud',
                'subcategory' => 'Medicamentos',
                'tags' => ['salud', 'medicamentos', 'primeros auxilios', 'emergencia', 'básico'],
                'stock_quantity' => 20,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 180.00,
                'suggested_price' => 220.00,
                'currency' => 'GTQ',
                'weight' => 0.8,
                'length' => 25,
                'width' => 20,
                'height' => 12,
                'is_active' => true,
                'is_featured' => false,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de farmacéutica',
                'received_date' => now()->subDays(6),
                'condition' => 'new',
                'specifications' => [
                    'Contenido' => 'Vendas, gasas, alcohol, agua oxigenada, termómetro',
                    'Uso' => 'Primeros auxilios',
                    'Caducidad' => '2 años',
                    'Tipo' => 'Básico',
                    'Edad' => 'Todas las edades'
                ],
                'usage_instructions' => 'Kit esencial para atención de emergencias básicas.',
                'care_instructions' => 'Mantener en lugar fresco y seco, revisar fechas de caducidad.',
                'ngo_notes' => 'Kit médico esencial para comunidades sin acceso a servicios de salud.',
                'created_by' => $users->skip(1)->first()?->id,
            ],
            [
                'name' => 'Herramientas de Jardinería',
                'description' => 'Set de herramientas de jardinería que incluye: pala, rastrillo, regadera, guantes y semillas de hortalizas. Para proyectos de agricultura familiar.',
                'short_description' => 'Set completo de herramientas de jardinería',
                'category' => 'Agricultura',
                'subcategory' => 'Herramientas',
                'tags' => ['agricultura', 'herramientas', 'jardinería', 'semillas', 'cultivo'],
                'stock_quantity' => 15,
                'stock_status' => 'in_stock',
                'manage_stock' => true,
                'cost_price' => 250.00,
                'suggested_price' => 300.00,
                'currency' => 'GTQ',
                'weight' => 2.5,
                'length' => 50,
                'width' => 30,
                'height' => 15,
                'is_active' => true,
                'is_featured' => false,
                'is_digital' => false,
                'requires_shipping' => true,
                'donation_source' => 'Donación de cooperativa agrícola',
                'received_date' => now()->subDays(14),
                'condition' => 'good',
                'specifications' => [
                    'Incluye' => 'Pala, rastrillo, regadera, guantes, semillas',
                    'Material' => 'Acero y plástico',
                    'Uso' => 'Jardinería y agricultura familiar',
                    'Semillas' => 'Tomate, lechuga, cebolla, zanahoria',
                    'Tamaño' => 'Familiar'
                ],
                'usage_instructions' => 'Ideal para proyectos de agricultura familiar y huertos comunitarios.',
                'care_instructions' => 'Limpiar después de usar, mantener en lugar seco.',
                'ngo_notes' => 'Herramientas en buen estado, perfectas para programas de seguridad alimentaria.',
                'created_by' => $users->skip(2)->first()?->id,
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }

        $this->command->info('Productos de muestra creados exitosamente.');
    }
}
