<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Sponsor;
use App\Models\Project;

class SponsorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sponsors = [
            [
                'name' => 'Fundación Carlos Slim',
                'company_name' => 'Fundación Carlos Slim',
                'contact_person' => 'María González',
                'email' => 'contacto@fundacioncarlosslim.org',
                'phone' => '+52 55 1234-5678',
                'address' => 'Av. Insurgentes Sur 1602, Piso 9, Col. San José Insurgentes, Ciudad de México',
                'website' => 'https://fundacioncarlosslim.org',
                'sponsor_type' => 'foundation',
                'contribution_type' => 'monetary',
                'contribution_amount' => 50000.00,
                'contribution_description' => 'Apoyo financiero para construcción de viviendas en comunidades rurales',
                'status' => 'active',
                'partnership_start_date' => '2023-01-15',
                'partnership_end_date' => '2025-12-31',
                'description' => 'Fundación comprometida con el desarrollo social y la construcción de viviendas dignas en Latinoamérica.',
                'notes' => 'Contacto principal establecido. Muy receptivos a proyectos de vivienda social.',
                'is_featured' => true,
                'priority_level' => 9,
            ],
            [
                'name' => 'Constructora Nacional S.A.',
                'company_name' => 'Constructora Nacional S.A.',
                'contact_person' => 'Roberto Martínez',
                'email' => 'r.martinez@constructoranacional.com',
                'phone' => '+502 2222-3333',
                'address' => 'Zona 10, Ciudad de Guatemala, Guatemala',
                'website' => 'https://constructoranacional.com',
                'sponsor_type' => 'corporate',
                'contribution_type' => 'mixed',
                'contribution_amount' => 25000.00,
                'contribution_description' => 'Materiales de construcción y mano de obra especializada',
                'status' => 'active',
                'partnership_start_date' => '2023-06-01',
                'description' => 'Empresa constructora con más de 20 años de experiencia en proyectos sociales.',
                'notes' => 'Proveen materiales con descuento del 30% y personal técnico especializado.',
                'is_featured' => true,
                'priority_level' => 8,
            ],
            [
                'name' => 'Dr. Ana Patricia López',
                'company_name' => null,
                'contact_person' => 'Dr. Ana Patricia López',
                'email' => 'ana.lopez@email.com',
                'phone' => '+502 4444-5555',
                'address' => 'Antigua Guatemala, Sacatepéquez, Guatemala',
                'sponsor_type' => 'individual',
                'contribution_type' => 'monetary',
                'contribution_amount' => 10000.00,
                'contribution_description' => 'Donación personal para proyectos de vivienda en Antigua Guatemala',
                'status' => 'active',
                'partnership_start_date' => '2024-03-15',
                'description' => 'Médica retirada comprometida con el desarrollo comunitario local.',
                'notes' => 'Donante recurrente. Interesada en proyectos específicos de Antigua Guatemala.',
                'is_featured' => false,
                'priority_level' => 6,
            ],
            [
                'name' => 'USAID Guatemala',
                'company_name' => 'United States Agency for International Development',
                'contact_person' => 'Jennifer Smith',
                'email' => 'jennifer.smith@usaid.gov',
                'phone' => '+502 2333-4444',
                'address' => 'Embajada de Estados Unidos, Zona 10, Ciudad de Guatemala',
                'website' => 'https://www.usaid.gov/guatemala',
                'sponsor_type' => 'government',
                'contribution_type' => 'monetary',
                'contribution_amount' => 100000.00,
                'contribution_description' => 'Fondo para desarrollo comunitario y construcción de viviendas sostenibles',
                'status' => 'active',
                'partnership_start_date' => '2023-09-01',
                'partnership_end_date' => '2026-08-31',
                'description' => 'Agencia gubernamental estadounidense enfocada en desarrollo internacional.',
                'notes' => 'Proyecto de 3 años. Requiere reportes trimestrales detallados.',
                'is_featured' => true,
                'priority_level' => 10,
            ],
            [
                'name' => 'Habitat for Humanity International',
                'company_name' => 'Habitat for Humanity International',
                'contact_person' => 'Carlos Mendoza',
                'email' => 'carlos.mendoza@habitat.org',
                'phone' => '+502 5555-6666',
                'address' => 'Zona 4, Ciudad de Guatemala, Guatemala',
                'website' => 'https://www.habitat.org/where-we-build/guatemala',
                'sponsor_type' => 'ngo',
                'contribution_type' => 'mixed',
                'contribution_amount' => 75000.00,
                'contribution_description' => 'Apoyo técnico, materiales y voluntarios internacionales',
                'status' => 'active',
                'partnership_start_date' => '2022-11-01',
                'description' => 'Organización internacional especializada en construcción de viviendas asequibles.',
                'notes' => 'Aliado estratégico principal. Proporcionan capacitación técnica y voluntarios.',
                'is_featured' => true,
                'priority_level' => 9,
            ],
            [
                'name' => 'Voluntarios Sin Fronteras',
                'company_name' => 'Voluntarios Sin Fronteras',
                'contact_person' => 'Laura Rodríguez',
                'email' => 'laura@voluntariossinfronteras.org',
                'phone' => '+502 7777-8888',
                'address' => 'Quetzaltenango, Guatemala',
                'website' => 'https://voluntariossinfronteras.org',
                'sponsor_type' => 'ngo',
                'contribution_type' => 'volunteer',
                'contribution_amount' => 5000.00,
                'contribution_description' => 'Voluntarios especializados en construcción y capacitación comunitaria',
                'status' => 'active',
                'partnership_start_date' => '2024-01-01',
                'description' => 'ONG local que coordina voluntarios para proyectos de desarrollo comunitario.',
                'notes' => 'Proporcionan 20-30 voluntarios por proyecto. Muy organizados y comprometidos.',
                'is_featured' => false,
                'priority_level' => 7,
            ],
            [
                'name' => 'Cementos Progreso',
                'company_name' => 'Cementos Progreso S.A.',
                'contact_person' => 'Miguel Ángel Castillo',
                'email' => 'miguel.castillo@cementosprogreso.com',
                'phone' => '+502 9999-0000',
                'address' => 'Zona 9, Ciudad de Guatemala, Guatemala',
                'website' => 'https://www.cementosprogreso.com',
                'sponsor_type' => 'corporate',
                'contribution_type' => 'materials',
                'contribution_amount' => 15000.00,
                'contribution_description' => 'Cemento y materiales de construcción con descuento especial',
                'status' => 'active',
                'partnership_start_date' => '2023-04-01',
                'description' => 'Empresa líder en producción de cemento en Centroamérica.',
                'notes' => 'Descuento del 40% en cemento. Entrega directa a obras.',
                'is_featured' => false,
                'priority_level' => 8,
            ],
            [
                'name' => 'Fundación Tigo',
                'company_name' => 'Fundación Tigo',
                'contact_person' => 'Sandra Morales',
                'email' => 'sandra.morales@tigo.com.gt',
                'phone' => '+502 1111-2222',
                'address' => 'Zona 10, Ciudad de Guatemala, Guatemala',
                'website' => 'https://fundaciontigo.com',
                'sponsor_type' => 'corporate',
                'contribution_type' => 'monetary',
                'contribution_amount' => 30000.00,
                'contribution_description' => 'Fondo para proyectos de tecnología y desarrollo comunitario',
                'status' => 'pending',
                'partnership_start_date' => '2024-06-01',
                'description' => 'Fundación corporativa enfocada en educación y desarrollo tecnológico.',
                'notes' => 'Proyecto en evaluación. Interesados en incorporar tecnología a las viviendas.',
                'is_featured' => false,
                'priority_level' => 5,
            ],
        ];

        foreach ($sponsors as $sponsorData) {
            Sponsor::updateOrCreate(
                ['email' => $sponsorData['email']],
                $sponsorData
            );
        }
    }
}